# Generated by Django 3.0.8 on 2021-08-30 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('units', models.CharField(choices=[('METERS', 'METERS'), ('PACKET', 'PACKET'), ('EXACT', 'EXACT')], max_length=200, null=True)),
                ('item_description', models.TextField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.Vendor')),
            ],
        ),
    ]
