# Generated by Django 3.0.8 on 2021-09-10 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='purchased_qty',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchased_qty',
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='price',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
