# Generated by Django 3.0.8 on 2021-10-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='units',
            field=models.CharField(blank=True, choices=[('METERS', 'METERS'), ('PACKET', 'PACKET')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='units',
            field=models.CharField(blank=True, choices=[('METERS', 'METERS'), ('PACKET', 'PACKET')], max_length=200, null=True),
        ),
    ]
