# Generated by Django 3.0.8 on 2021-09-04 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, null=True)),
                ('current_qty', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchased_qty', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchased_by', models.CharField(max_length=200, null=True)),
                ('vendor', models.CharField(max_length=200, null=True)),
                ('issued_qty', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('issued_by', models.CharField(max_length=200, null=True)),
                ('issued_to', models.CharField(max_length=200, null=True)),
                ('returneditems_qty', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('returned_by', models.CharField(max_length=200, null=True)),
                ('recieved_by', models.CharField(max_length=200, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('export', models.BooleanField(default=False)),
            ],
        ),
    ]
