# Generated by Django 3.0.8 on 2021-08-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='issuance',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
    ]
