# Generated by Django 3.0.8 on 2021-09-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvendor',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='historicalvendor',
            name='contact_person_phone',
        ),
        migrations.RemoveField(
            model_name='historicalvendor',
            name='other_details',
        ),
        migrations.RemoveField(
            model_name='historicalvendor',
            name='primary_contact_person',
        ),
        migrations.RemoveField(
            model_name='historicalvendor',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='historicalvendor',
            name='website',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='contact_person_phone',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='other_details',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='primary_contact_person',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='website',
        ),
    ]
