# Generated by Django 3.0.8 on 2021-09-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='quantity',
            new_name='purchased_qty',
        ),
    ]
