# Generated by Django 3.0.8 on 2021-08-25 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_auto_20210824_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
