# Generated by Django 3.0.8 on 2021-09-06 16:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_auto_20210906_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendor',
            name='billing_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='other_details',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='primary_contact_person',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='shipping_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='billing_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='other_details',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='primary_contact_person',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shipping_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvendor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
