# Generated by Django 3.0.8 on 2021-09-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_auto_20210910_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
    ]
