# Generated by Django 3.0.8 on 2021-08-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='vendor',
        ),
    ]
