# Generated by Django 3.0.8 on 2021-10-05 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_auto_20211005_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='item_description',
            field=models.TextField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='units',
            field=models.CharField(blank=True, choices=[('METERS', 'METERS'), ('PACKET', 'PACKET')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='units',
            field=models.CharField(blank=True, choices=[('METERS', 'METERS'), ('PACKET', 'PACKET')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
