# Generated by Django 3.0.8 on 2021-10-05 13:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_auto_20211005_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvendor',
            name='billing_address',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalvendor',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalvendor',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalvendor',
            name='other_details',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalvendor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='historicalvendor',
            name='primary_contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalvendor',
            name='shipping_address',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalvendor',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='billing_address',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='other_details',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='primary_contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_address',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
