# Generated by Django 3.0.8 on 2021-09-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_auto_20210910_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedetails',
            name='vendor',
        ),
    ]
