# Generated by Django 3.0.8 on 2021-10-09 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_auto_20211009_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstock',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='reorder_level',
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='reorder_level',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='status',
            field=models.CharField(choices=[('Low Stock', 'Low stock'), ('Stock Available', 'Stock Available'), ('Out of Stock', 'Out of Stock')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='reorder_level',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='stock',
            name='status',
            field=models.CharField(choices=[('Low Stock', 'Low stock'), ('Stock Available', 'Stock Available'), ('Out of Stock', 'Out of Stock')], max_length=200, null=True),
        ),
    ]
