# Generated by Django 3.0.8 on 2021-08-30 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_remove_item_vendor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requestproduct',
            new_name='Requestitem',
        ),
        migrations.RemoveField(
            model_name='issuance',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productreturn',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='requestitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='teamleaderissuance',
            name='products',
        ),
        migrations.AddField(
            model_name='issuance',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.Item'),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.Item'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.Item'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.Item'),
        ),
        migrations.AddField(
            model_name='teamleaderissuance',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.Item'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
