# Generated by Django 3.0.8 on 2021-08-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_auto_20210825_1423'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Return',
            new_name='Productreturn',
        ),
    ]
