# Generated by Django 3.0.8 on 2021-09-05 06:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_historicalengineer_historicalissuance_historicalitem_historicalpurchase_historicalrequestitem_histor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalengineer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='historicalvendor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
