# Generated by Django 3.0.8 on 2021-09-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_auto_20210906_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='name',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
