# Generated by Django 3.0.8 on 2021-08-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_returneditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuance',
            name='issuedto',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Teamleaderissuance',
        ),
    ]
