# Generated by Django 3.0.8 on 2021-09-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_auto_20210910_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstock',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='item',
        ),
        migrations.AddField(
            model_name='stock',
            name='item',
            field=models.ManyToManyField(to='inv.Item'),
        ),
    ]
