# Generated by Django 3.0.8 on 2021-09-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_auto_20210908_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstock',
            name='export',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='export',
        ),
    ]
