# Generated by Django 3.0.8 on 2021-10-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_auto_20211009_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
