# Generated by Django 3.0.8 on 2021-09-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_auto_20210905_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='units',
            field=models.CharField(choices=[('METERS', 'METERS'), ('PACKET', 'PACKET')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='units',
            field=models.CharField(choices=[('METERS', 'METERS'), ('PACKET', 'PACKET')], max_length=200, null=True),
        ),
    ]
