# Generated by Django 3.0.8 on 2021-09-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_auto_20210908_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstock',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='vendor',
        ),
    ]
