# Generated by Django 3.0.8 on 2021-09-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_auto_20210906_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstore',
            name='name',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
