# Generated by Django 3.0.8 on 2021-09-13 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_auto_20210913_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchase',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inv.Item'),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='item',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='issued_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Engineer'),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Item'),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Store'),
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='item',
        ),
        migrations.AddField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(default=5555, on_delete=django.db.models.deletion.CASCADE, to='inv.Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Vendor'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Item'),
        ),
        migrations.RemoveField(
            model_name='stock',
            name='item',
        ),
        migrations.AddField(
            model_name='stock',
            name='item',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='engineer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Engineer'),
        ),
    ]
