# Generated by Django 3.0.8 on 2021-08-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_auto_20210830_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productreturn',
        ),
    ]
