# Generated by Django 3.0.8 on 2021-09-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_auto_20210906_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalissuance',
            old_name='quantity',
            new_name='issuedqty',
        ),
        migrations.RenameField(
            model_name='historicalreturneditems',
            old_name='quantity',
            new_name='returnedqty',
        ),
        migrations.RenameField(
            model_name='issuance',
            old_name='quantity',
            new_name='issuedqty',
        ),
        migrations.RenameField(
            model_name='returneditems',
            old_name='quantity',
            new_name='returnedqty',
        ),
    ]
