# Generated by Django 3.0.8 on 2021-10-11 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('river', '0002_auto_20211003_1858'),
        ('inv', '0007_auto_20211010_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstore',
            name='teamleader',
        ),
        migrations.RemoveField(
            model_name='store',
            name='teamleader',
        ),
        migrations.AddField(
            model_name='engineer',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engineerrequest',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='engineerreturns',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='engineerstock',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='historicalengineer',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='historicalengineer',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalengineerrequest',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='historicalengineerreturns',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='historicalengineerstock',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='historicalstaff',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='historicalstaff',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='historicalstore',
            name='description',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalstore',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='historicalteamleader',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='historicalteamleader',
            name='store',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inv.Store'),
        ),
        migrations.AddField(
            model_name='historicalteamleader',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalteamleaderrequest',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='historicalteamleaderstock',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='historicalteamleadreturns',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='historicalvendorprice',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='item',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='staff',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='teamleader',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='teamleader',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Store'),
        ),
        migrations.AddField(
            model_name='teamleader',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamleaderrequest',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='teamleaderstock',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='teamleadreturns',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='vendorprice',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State'),
        ),
    ]
