# Generated by Django 3.0.8 on 2021-09-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_auto_20210913_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='item',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
