# Generated by Django 3.0.8 on 2021-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_auto_20210908_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvendor',
            name='billing_address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvendor',
            name='shipping_address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='billing_address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_address',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
