# Generated by Django 3.0.8 on 2021-09-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_auto_20210906_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='itemtype',
            field=models.CharField(choices=[('Service', 'Service'), ('Goods', 'Goods')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='sku',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='billingaddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='otherdetails',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='primarycontactperson',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='shippingaddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='itemtype',
            field=models.CharField(choices=[('Service', 'Service'), ('Goods', 'Goods')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='billingaddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='otherdetails',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='primarycontactperson',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shippingaddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='employee_number',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalengineer',
            name='email',
            field=models.EmailField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalengineer',
            name='employee_number',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
