# Generated by Django 3.0.8 on 2021-10-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_auto_20211011_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='historicalengineer',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='historicalstaff',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='historicalstore',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='historicalteamleader',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='item',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='store',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='teamleader',
            name='my_state_field',
        ),
    ]
