# Generated by Django 3.0.8 on 2021-10-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0009_auto_20211011_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineerrequest',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='engineerreturns',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='engineerstock',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='historicalengineerrequest',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='historicalengineerreturns',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='historicalengineerstock',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='historicalstock',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='historicalteamleaderrequest',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='historicalteamleaderstock',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='historicalteamleadreturns',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='historicalvendor',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='historicalvendorprice',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='teamleaderrequest',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='teamleaderstock',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='teamleadreturns',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='my_state_field',
        ),
        migrations.RemoveField(
            model_name='vendorprice',
            name='my_state_field',
        ),
    ]
