# Generated by Django 3.0.8 on 2021-08-30 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0009_auto_20210830_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='returneditems',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.Store'),
        ),
    ]
