# Generated by Django 3.0.8 on 2021-10-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0010_auto_20211011_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitem',
            name='current_qty',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='issued_qty',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='purchased_qty',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='returned_qty',
        ),
        migrations.RemoveField(
            model_name='item',
            name='current_qty',
        ),
        migrations.RemoveField(
            model_name='item',
            name='issued_qty',
        ),
        migrations.RemoveField(
            model_name='item',
            name='purchased_qty',
        ),
        migrations.RemoveField(
            model_name='item',
            name='returned_qty',
        ),
    ]
