# Generated by Django 3.0.8 on 2021-09-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0013_auto_20210901_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='po',
        ),
    ]
