# Generated by Django 3.0.8 on 2021-10-13 16:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0014_auto_20211011_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='items',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='items',
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.VendorPrice')),
                ('po', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.ManyToManyField(through='inv.PurchaseItem', to='inv.VendorPrice'),
        ),
    ]
