# Generated by Django 3.0.8 on 2021-09-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0015_auto_20210901_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='status',
        ),
    ]
